@startuml PackageDiagram.backend

skinparam Dpi 100
skinparam DefaultFont {
    Name Monospace
    Size 13
    Style bold
}

namespace Backend {
    package _utilities {
        'method gps_to_location()
        class City
        class Time
        class Message
        class Utilities
        enum Gender
        enum Visibility
    }
    package _server{
        class Server
        interface Interface
    }
    'package _interface {}

    package _travel {
        class Travel
        class TravelGroup
        class TravelInfo
    }

    package _user {
        class User
        class UserInfoBase
        class UserInfo
        class FriendInfo
    }
}

package django {
}

namespace Frontend{
    package _view{
        abstract class MainBasicView
        class FriendView
        class MapView
        class MapComponent
        class ProfileView
        abstract class EntranceBasicView
        class LoginView
        class RegisterView
        
    }
    package _components{
            class HeaderComponent
            class RegisterComponent
            class LoginComponent
            class BackgroundComponent
            class NavigationComponent
            class FriendRequestComponent
            class UserInfoComponent
        }
    package _controller{
        class UserInfoController
        class CityInfoController
        class TravelController
    }
    package _model{
        class Model
    }
}

package leaflet.js{
    class Map
}
package Vue.js{
    
}

User        *--  UserInfo
User        *--  FriendInfo
User        *--  TravelGroup
UserInfo    --|> UserInfoBase
FriendInfo  --|> UserInfoBase
TravelGroup o--  Travel
Travel      *--  TravelInfo
Travel      <..  User
Travel      <..  FriendInfo
TravelInfo  o--  City
TravelInfo  *--  Time


Model .down.> Server
Server ..|> Interface

MapView ..> Map
MapView .> MapComponent

MainBasicView <|-- FriendView
MainBasicView <|-- MapView
MainBasicView <|-- ProfileView
EntranceBasicView <|-- LoginView
EntranceBasicView <|-- RegisterView

ProfileView ..> UserInfoComponent
ProfileView ..> FriendRequestComponent
MainBasicView ..> HeaderComponent
MainBasicView ..> NavigationComponent
LoginView ..>LoginComponent
RegisterView ..>RegisterComponent
EntranceBasicView ..> BackgroundComponent

_server    ..> django:    <<import>>
_travel    ..> _utilities: <<access>>
_user      .down.> _utilities: <<access>>
_server ..> _travel:    <<import>>
_server ..> _user:      <<import>>
_view ..> Vue.js: <<import>>
_view ..> _components: <<import>>
@enduml
