@startuml PackageDiagram

skinparam Dpi 200
skinparam DefaultFont {
    Name Menlo
    Size 13
    Style bold
}

namespace Backend {
    package _server{
        class Server
        interface Interface
    }

    package _user {
        class User
        class UserInfoBase
        class UserInfo
        class FriendInfo
    }

    package _travel {
        class Travel
        class TravelGroup
        class TravelInfo
    }

    package _utilities {
        ' method gps_to_location()
        class City
        class Time
        class Message
        class Utilities
        enum Gender
        enum Visibility
    }
}

package django {
}

namespace Frontend {
    package _model {
        class Model
    }

    package _controller {
        class UserInfoController
        class CityInfoController
        class TravelController
    }

    package _view {
        abstract class MainBasicView
        class FriendView
        class MapView
        class MapComponent
        class ProfileView
        abstract class EntranceBasicView
        class LoginView
        class RegisterView

    }

    package _components {
        class HeaderComponent
        class RegisterComponent
        class LoginComponent
        class BackgroundComponent
        class NavigationComponent
        class FriendRequestComponent
        class UserInfoComponent
    }
}

package Vue.js {
}

package leaflet.js {
    class Map
}

_view   .right.> Vue.js      : <<import>>
_server .right.> django      : <<import>>
MapView .down.>  Map

Model .right.> Server

MainBasicView     <|-down- FriendView
MainBasicView     <|-down- MapView
MainBasicView     <|-down- ProfileView
EntranceBasicView <|-down- LoginView
EntranceBasicView <|-down- RegisterView
MapView .right.> MapComponent

EntranceBasicView .down.> BackgroundComponent
LoginView         .down.> LoginComponent
RegisterView      .down.> RegisterComponent
MainBasicView     .down.> HeaderComponent
MainBasicView     .down.> NavigationComponent
ProfileView       .down.> UserInfoComponent
ProfileView       .down.> FriendRequestComponent

Server       .right.|> Interface
User         *-down-   UserInfo
User         *-down-   FriendInfo
User         *-right-  TravelGroup
UserInfo     -down-|>  UserInfoBase
FriendInfo   -down-|>  UserInfoBase
UserInfoBase o-down-   City
TravelGroup  *-down-   Travel
Travel       *-down-   TravelInfo
User         -down->   Travel
FriendInfo   -right->  Travel
TravelInfo   o-down-   City
TravelInfo   *-down-   Time

_view   .down.>  _components : <<import>>
_server .down.>  _user       : <<import>>
_server .down.>  _travel     : <<import>>
_user   .down.>  _utilities  : <<access>>
_travel .down.>  _utilities  : <<access>>

@enduml
