@startuml

skinparam classAttributeIconSize 0
skinparam Dpi 300
skinparam DefaultFontName Menlo
skinparam DefaultFontSize 11
skinparam DefaultFontStyle bold
skinparam ClassFontSize 13

namespace backend {

    User "1..1" *-- "1..*" UserInfo
    User "1..1" *-- "0..*" TravelGroup
    TravelGroup "1..1" o-- "0..*" Travel
    Travel "1..1" *-- "1..1" TravelInfo
    Travel "1..*" <.. "0..*" User
    Travel "1..*" <.. "0..*" UserInfo
    TravelInfo "1..1" o-- "1..1" City

    class User {
        - user_id: int {readonly,frozen}
        - user_info: UserInfo
        - friend_info_list: UserInfo[0..*]
        - friend_note_list: str[0..*]
        - travel_group_list: TravelGroup[0..*]
        + get_user_id(): int
        + get_user_info(): UserInfo
        + get_friend_info_list(): UserInfo[0..*]
        + get_friend_note_list(): str[0..*]
        + get_travel_group_list(): TravelGroup[0..*]
        + add_travel_group(): int
        + del_travel_group(travel_group_id: int): int
    }

    class UserInfo {
        - user_id: int {readonly,frozen}
        - user_name: str
        - email: str
        - gender: Gender
        - resident_city: City
        + get_user_id(): int
        + get_user_name(): str
        + set_user_name(user_name: str): int
        + get_email(): str
        + set_email(email: str): int
        + get_gender(): Gender
        + set_gender(gender: Gender): int
        + get_resident_city(): City
        + set_resident_city(city_id: int): int
    }

    class TravelGroup {
        - user_id: int {readonly,frozen}
        - travel_group_id: int {readonly,frozen}
        - travel_group_note: str
        - travel_list: Travel[0..*]
        + get_user_id(): int
        + get_travel_group_id(): int
        + get_travel_group_note(): str
        + set_travel_group_note(travel_group_note: str): int
        + get_travel_list(): Travel[0..*]
        + add_travel(): int
        + del_travel(travel_id: int): int
    }

    class Travel {
        - user_id: int {readonly,frozen}
        - travel_id: int {readonly,frozen}
        - travel_info: TravelInfo
        - company_user_id_list: int[0..*]
        + get_user_id(): int
        + get_travel_id(): int
        + get_travel_info(): TravelInfo
        + add_company(company_user_id: int): int
        + del_company(company_user_id: int): int
        + move_to_travel_group(travel_group_id: int): int
        + move_to_new_travel_group(): int[2..2]
    }

    class TravelInfo {
        - user_id: int {readonly,frozen}
        - travel_id: int {readonly,frozen}
        - travel_note: str
        - city: City
        - time_start: int
        - time_end: int
        - visibility: Visibility
        + get_user_id(): int
        + get_travel_id(): int
        + get_travel_note(): str
        + set_travel_note(travel_note: str): int
        + get_city(): City
        + set_city(city_id: int): int
        + get_time_start(): int
        + set_time_start(time_start: int): int
        + get_time_end(): int
        + set_time_end(time_end: int): int
        + get_visibility(): Visibility
        + set_visibility(visibility: Visibility): int
    }

    class City {
        + city_id: int {readonly,frozen}
        + city_name: str {readonly,frozen}
        + latitude: float {readonly,frozen}
        + longitude: float {readonly,frozen}
    }
}

@enduml
