# Generated by Django 2.1.7 on 2019-05-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cities', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user_id', to='Users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGroupOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGroups',
            fields=[
                ('travel_groups_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('travel_groups_note', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('travel_id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_start', models.DateField(db_index=True)),
                ('data_end', models.DateField(db_index=True)),
                ('visibility', models.CharField(choices=[('M', 'Only Me'), ('F', 'Friend'), ('P', 'Public')], default='F', max_length=1)),
                ('travel_note', models.TextField(max_length=140)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cities.Cities')),
            ],
        ),
        migrations.AddField(
            model_name='travelgroupownership',
            name='travel_groups_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Travels.TravelGroups'),
        ),
        migrations.AddField(
            model_name='travelgroupownership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
        migrations.AddField(
            model_name='travelgrouping',
            name='travel_groups_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Travels.TravelGroups'),
        ),
        migrations.AddField(
            model_name='travelgrouping',
            name='travel_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Travels.Travels'),
        ),
        migrations.AddField(
            model_name='travelassociation',
            name='travel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels.Travels'),
        ),
        migrations.AlterUniqueTogether(
            name='travelassociation',
            unique_together={('travel_id', 'company_user_id')},
        ),
    ]
